# Generated by Django 6.0.6 on 2026-06-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
    ]
