# Generated by Django 6.0.6 on 2026-08-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalrequest",
            name="delivery_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalrequest",
            name="delivery_contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="rentalrequest",
            name="fulfillment_type",
            field=models.CharField(
                choices=[("PICKUP", "In-Person Pickup"), ("DELIVERY", "Delivery")],
                default="PICKUP",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rentalrequest",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
