# Generated by Django 6.0.6 on 2026-07-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="equipment",
            constraint=models.UniqueConstraint(
                fields=("owner", "title"), name="unique_owner_equipment_title"
            ),
        ),
    ]
