# Generated by Django 6.0.6 on 2026-08-16 08:14

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0002_rentalrequest_delivery_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalrequest",
            name="delivery_contact_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
