# Generated by Django 6.0.6 on 2026-07-07 07:33

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0003_equipment_unique_owner_equipment_title"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="equipment",
            name="unique_owner_equipment_title",
        ),
        migrations.AddConstraint(
            model_name="equipment",
            constraint=models.UniqueConstraint(
                models.F("owner"),
                django.db.models.functions.text.Lower("title"),
                name="unique_owner_equipment_title",
            ),
        ),
    ]
