# Generated by Django 6.0.6 on 2026-08-16 15:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0003_alter_rentalrequest_delivery_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="daily_rent",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
