# Generated by Django 6.0.6 on 2026-07-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0004_remove_equipment_unique_owner_equipment_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
