# Generated by Django 6.0.6 on 2026-08-20 09:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0004_alter_equipment_daily_rent"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="address_name",
            field=models.CharField(
                blank=True,
                help_text="Human-readable address e.g. Banani, Dhaka",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, db_index=True, null=True, srid=4326
            ),
        ),
    ]
