# Generated by Django 6.0.6 on 2026-08-21 11:34

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0005_equipment_address_name_equipment_location"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="equipment",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["address_name"],
                name="address_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
