# Generated by Django 6.0.6 on 2026-07-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0005_equipment_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="purchase_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="rent_advance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
