# Generated by Django 6.0.6 on 2026-07-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0006_alter_equipment_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={"ordering": ["-created_at"]},
        ),
    ]
