# Generated by Django 6.0.6 on 2026-07-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0007_alter_equipment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="equipment_thumbnails/"
            ),
        ),
    ]
