# Generated by Django 6.0.6 on 2026-07-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0008_equipment_thumbnail_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="thumbnail_image",
            field=models.ImageField(default="", upload_to="equipment_thumbnails/"),
            preserve_default=False,
        ),
    ]
